### ISSUE TITLE
IE Support?

### ISSUE THREAD

**Issue by spinlock99** [jariz/react-truncate-html#3]
Unfortunately, I have to support IE and I'm running into an issue with `react-truncate-html`. The code you're generating is using `Symbol` which isn't supported yet. Is there any way to tweak the build so that you output an older version of Javascript?

I'll also look into this an (hopefully) submit a patch. But, I'd love any pointers you could offer.

Thanks!

**Comment by jariz** [comment]
Hmmm I wonder why Babel would include a feature in its output that isn't supported in IE at all. 🤔
Eitherway, there should probably be a option to change the ES version of the output, I'll look into it.

**Comment by jariz** [comment]
Hey so I think I fixed this in b265b95ec3b5e8aa86d2f8a9a715db293c0c0c16, unfortunately I'm rather lazy, so can you update to 0.1.4 and confirm with me that this fixed it for you?

**Comment by spinlock99** [comment]
now I'm getting the error: `Truncate not defined`. the project I'm working on is using typescript and importing `Truncate` was touch and go before this change. I tried add `transform-runtime` as a babble plugin in `.babelrc` and that did seem to resolve the `Symbol` issue (although there were others that are still blocking).

**Comment by jariz** [comment]
All I did was add the babel polyfill to the index, the exports didn't change which will fill in the missing Symbol, etc.  
You're importing it as `import Truncate from 'react-truncate-html'` and not `import Truncate from 'react-truncate-html/Truncate'` right?
I'll take a look at my own project to see if everything's still working.

**Comment by spinlock99** [comment]
I was doing `import Truncate from "react-truncate-html"` which is actually different from how I would normally import a function. In ts, you need to do `import * as Truncate from "react-truncate-thml"` or, preferably, `import { Truncate } from "react-truncate-html"`

so, I think stuffing the polyfill into the source did make ts barf.

sorry that I can't be more help. I'm not really familiar with all of the different flavors of js exports.

**Comment by spinlock99** [comment]
p.s. please feel free to close this issue if it's not helpful to you. And, thanks for putting together a cool package that works well on good browsers :)

**Comment by jariz** [comment]
Stuffing the polyfill into the source just made a project that was using the polyfill too crash.  
So, I gotta find another way...

**Comment by stanley90** [comment]
I used version 0.1.3 because had the babel-polyfill problem too. It works in FF and IE11, but on IE10, it freezes the browser (only in case truncation takes place, it works for short texts).

**Comment by jariz** [comment]
Polyfill has been removed in #7, you're responsible for adding it yourself (will be added to the readme)

**Comment by tom-daly** [comment]
> I used version 0.1.3 because had the babel-polyfill problem too. It works in FF and IE11, but on IE10, it freezes the browser (only in case truncation takes place, it works for short texts).

You are saying that you are able to get to work with v0.1.3 & babel-polyfill? I only have to support IE 11 and I'm finding that it does not work in IE 11. Used the poly-fill works but then get hit with long running scripts. It seems to be getting caught inside itself.
