### ISSUE TITLE
Is it safe for user-created content?

### ISSUE THREAD

**Issue by machadogj** [jariz/react-truncate-html#4]
Is the `dangerouslySetInnerHTML` not dangerous for content created by the user? If so, I would strongly urge you to add this very clearly to the documentation.
For reference: http://stackoverflow.com/questions/35800607/when-can-i-consider-my-use-of-dangerouslysetinnerhtml-safe
Cheers!

**Comment by jariz** [comment]
I figured it was kind of obvious (the name is react-truncate-html after all, so it's gonna execute HTML), but it can't hurt to clarify, yea.  
I've updated the readme, is this to your likings?

**Comment by machadogj** [comment]
@jariz the update to the docs looks great! I've checked the package you proposed and looks good as well. It's only ~370 lines of code, so it kinda begs the question of why not include this by default with maybe a `skipSanitization` flag (or even a `sanitize` one to opt in).

**Comment by jariz** [comment]
While sure probably useful, it's generally just standard practice to not let the client handle any unsafe HTML in the first place.   
It even says so in the sanitize-html docs:  

> _Think first: why do you want to use it in the browser?_ Remember, _servers must never trust browsers._ You can't sanitize HTML for saving on the server anywhere else but on the server.   

I don't really wanna encourage client side sanitation, and I don't think the extra dependencies are worth it either. sanitize-html might have 370 lines itself, but it's main dependency, htmlparser2, is a tad bigger (~3000 lines).
